### ISSUE TITLE
Running on AMD 7900xtx Archlinux

### ISSUE THREAD

**Issue by andzejsp** [character-ai/Ovi#34]
Any way to run this on archlinux 7900xtx?

Im having problem with flash-attn. Cant seem to find a working way to build that module.. and without it i cant launch th eapp

**Comment by TaturasLegend** [comment]
> > > > > any chance running this with 24gb vram? im getting oom error :(
> > > > 
> > > > 
> > > > You're using the fp8 version ? Even on nvidia 4090 I need to run the fp8 version and it runs fine with my nvidia at around 18gb ish with flash attention and around 16 with sage, so should still potentially work on AMD as well - there are bits of help with Triton and Attentions etc over on SDNexts discord on the ROCM and Zluda threads ie where I've seen the most chat on it.
> > > 
> > > 
> > > Yes i use fp8 and yes it uses less than 16gb while it renders the 50 iterations but after that it tries to allocate more vram than the gpu has and throws OOM.
> > > I dont have discord, and without trinitron Bromcom you would not be able to launch the app. Im using 7900xtx aswell.. so yeah.. if anyone has a working script of additional packages to install i would appretiate the help.
> > > I even tried to lower the video resolution from the default that the gradio app had to 480x480 and 320x320 and it used up the same ammount of Vram and errored with OOM.
> > 
> > 
> > The problem I noted in the Discord was that the vae decode is taking too much vram on amd gpus (rocm 6.4, rock and ZLuda - don't know about rocm 7) and the 'solution' has been using a tiled decode. Not a solution for ovi at the moment, there might be other solutions on the discord but I mostly use my nvidia gpu (so there's a bit of 'in one ear and out the other')
> 
> Its unfortunate that AMD is behind on computing.. 7900xtx is solid and cheap compared to NVIDIA.. even used 4090 is 3x or more expensive than 7900xtx..
> 
> Yes in comfyUI it automagically switches to tiled decode, to not crash.. hmm.. is this a model limitation or how does this work? Can it be fixed in code to eneable that tiled thing? Can this not be offloaded wholy on to CPU RAM? I got loads of ram.. not enough Vram.. I dont mind waiting extra minute for data transfers from Vram to RAM..
> 
> As for OP:
> 
> This worked for me:
> 
> ```
> # Clone the repository
> git clone https://github.com/character-ai/Ovi.git
> 
> cd Ovi
> 
> # Create and activate virtual environment
> 
> python3.12 -m venv ./venv
> source venv/bin/activate
> 
> pip install --force-reinstall torch==2.5.1 torchaudio==2.5.1 torchvision==0.20.1 --index-url https://download.pytorch.org/whl/rocm6.2
> 
> pip install torch torchaudio torchvision pytorch-triton-rocm --index-url https://download.pytorch.org/whl/rocm6.2
> 
> # Install other dependencies
> pip install -r requirements.txt
> 
> # install this
> pip uninstall pytorch-triton-rocm triton -y
> git clone https://github.com/ROCm/triton.git
> cd triton/python
> pip install pybind11
> MAX_JOBS=$((`nproc` - 3)) GPU_ARCHS=gfx1100 python setup.py install
> cd ../..
> 
> # then install this
> git clone https://github.com/ROCm/flash-attention.git
> cd flash-attention/
> MAX_JOBS=$((`nproc` - 3)) GPU_ARCHS=native FLASH_ATTENTION_TRITON_AMD_ENABLE="TRUE" python setup.py install
> cd ..
> 
> # Add export variable
> 
> export FLASH_ATTENTION_TRITON_AMD_ENABLE="TRUE"
> 
> # Run app
> python3 gradio_app.py --cpu_offload --fp8
> ```
> 
> But it crashes due to OOM -> [#36](https://github.com/character-ai/Ovi/issues/36)

I've tried it with dual RX 7900 XTX on 3 distributions and both pytorch from ROCm 6.4 and ROCm 7.0. Didn't work. OOM on VAE decode. Even tried to modify code to do VAE separately after denoise. Guess we must do something with tiling in code.

**Comment by Helikaon23s** [comment]
> > > > > > any chance running this with 24gb vram? im getting oom error :(
> > > > > 
> > > > > 
> > > > > You're using the fp8 version ? Even on nvidia 4090 I need to run the fp8 version and it runs fine with my nvidia at around 18gb ish with flash attention and around 16 with sage, so should still potentially work on AMD as well - there are bits of help with Triton and Attentions etc over on SDNexts discord on the ROCM and Zluda threads ie where I've seen the most chat on it.
> > > > 
> > > > 
> > > > Yes i use fp8 and yes it uses less than 16gb while it renders the 50 iterations but after that it tries to allocate more vram than the gpu has and throws OOM.
> > > > I dont have discord, and without trinitron Bromcom you would not be able to launch the app. Im using 7900xtx aswell.. so yeah.. if anyone has a working script of additional packages to install i would appretiate the help.
> > > > I even tried to lower the video resolution from the default that the gradio app had to 480x480 and 320x320 and it used up the same ammount of Vram and errored with OOM.
> > > 
> > > 
> > > The problem I noted in the Discord was that the vae decode is taking too much vram on amd gpus (rocm 6.4, rock and ZLuda - don't know about rocm 7) and the 'solution' has been using a tiled decode. Not a solution for ovi at the moment, there might be other solutions on the discord but I mostly use my nvidia gpu (so there's a bit of 'in one ear and out the other')
> > 
> > Its unfortunate that AMD is behind on computing.. 7900xtx is solid and cheap compared to NVIDIA.. even used 4090 is 3x or more expensive than 7900xtx..
> > 
> > Yes in comfyUI it automagically switches to tiled decode, to not crash.. hmm.. is this a model limitation or how does this work? Can it be fixed in code to eneable that tiled thing? Can this not be offloaded wholy on to CPU RAM? I got loads of ram.. not enough Vram.. I dont mind waiting extra minute for data transfers from Vram to RAM..
> > 
> > As for OP:
> > 
> > This worked for me:
> > 
> > ```
> > # Clone the repository
> > git clone https://github.com/character-ai/Ovi.git
> > 
> > cd Ovi
> > 
> > # Create and activate virtual environment
> > 
> > python3.12 -m venv ./venv
> > source venv/bin/activate
> > 
> > pip install --force-reinstall torch==2.5.1 torchaudio==2.5.1 torchvision==0.20.1 --index-url https://download.pytorch.org/whl/rocm6.2
> > 
> > pip install torch torchaudio torchvision pytorch-triton-rocm --index-url https://download.pytorch.org/whl/rocm6.2
> > 
> > # Install other dependencies
> > pip install -r requirements.txt
> > 
> > # install this
> > pip uninstall pytorch-triton-rocm triton -y
> > git clone https://github.com/ROCm/triton.git
> > cd triton/python
> > pip install pybind11
> > MAX_JOBS=$((`nproc` - 3)) GPU_ARCHS=gfx1100 python setup.py install
> > cd ../..
> > 
> > # then install this
> > git clone https://github.com/ROCm/flash-attention.git
> > cd flash-attention/
> > MAX_JOBS=$((`nproc` - 3)) GPU_ARCHS=native FLASH_ATTENTION_TRITON_AMD_ENABLE="TRUE" python setup.py install
> > cd ..
> > 
> > # Add export variable
> > 
> > export FLASH_ATTENTION_TRITON_AMD_ENABLE="TRUE"
> > 
> > # Run app
> > python3 gradio_app.py --cpu_offload --fp8
> > ```
> > 
> > But it crashes due to OOM -> [#36](https://github.com/character-ai/Ovi/issues/36)
> 
> I've tried it with dual RX 7900 XTX on 3 distributions and both pytorch from ROCm 6.4 and ROCm 7.0. Didn't work. OOM on VAE decode. Even tried to modify code to do VAE separately after denoise. Guess we must do something with tiling in code.

Is that with the Kijais wan wrapper workflow with the fp8 model ? as that has vae tiling as I recall

**Comment by TaturasLegend** [comment]
> Is that with the Kijais wan wrapper workflow with the fp8 model ? as that has vae tiling as I recall

Haven't tried ComfyUI yet. I'll do that today after my work. Would be great if tiling would work in inference too.

**Comment by TaturasLegend** [comment]
Finally got it working on inference, but I've got 31 frames only, due to "video_latent_length = 31" I guess. What I did was modified decode function to decode frame by frame over whole chunk and it worked. Video is very short and super fast and audio is good. LLM suggested that I need interpolation function, but couldn't get it working yet. Any ideas how to fix it would be welcome. Thanks.

**Comment by TaturasLegend** [comment]
> is it already merged in the repo and working? how long did it take to generate those 31 frames at what resolution? also can it generate longer videos?

Nothing was merged, I am not member of this projet, I'm just experimenting. What you want is to look at wae2_2.py which is in Ovi/ovi/modules directory. Look at the last class at the end where decode methods are, there you can modify code to decode in chunks. There is a problem with Tepmoral shape, it only generates every 4th frame so video is not what it suppose to be. Reducing frame rate or interpolation is not an option. Might need to find a way to generate 4 chunks of 31 frames and add them up before decoding.

P.S. I will share changes if I'll succeed in making whole 5s video as it suppose to be.

**Comment by TaturasLegend** [comment]
Wan2GP works fine on RX7900XTX, you just have to install pytorch 2.7, I've tried it. https://github.com/deepbeepmeep/Wan2GP?tab=readme-ov-file.
